### ISSUE TITLE
jdbc_driver_library does not support several jar libraries

### ISSUE THREAD

**Issue by jguay** [logstash-plugins/logstash-filter-jdbc_static#22]
jdbc_static setting jdbc_driver_library only seems to support a single jar file

In the attached logstash-static.conf the following works fine for input jdbc but fails for filter jdbc_static:
```
jdbc_driver_library => "/Users/julien/Downloads/logstash-6.2.3/config/mysql-connector-java-5.1.45-bin.jar,/Users/julien/Downloads/logstash-6.2.3/config/mysql-connector-java-5.1.45-bin.jar"
```

Reproduction steps:
1- Unzip 
[mysql.zip](https://github.com/logstash-plugins/logstash-filter-jdbc_static/files/1919421/mysql.zip)

2- Add in unzipped folder file mysql-connector-java-5.1.46-bin.jar which can be downloaded [here](https://dev.mysql.com/downloads/connector/j/5.1.html)

3- From the main folder optionally run "docker-compose up -d mysql-db", then run "docker-compose up logstash"; this will pull and start mysql (with a few rows of data in 2 tables) and then logstash 6.2.3 which will fail with current config/logstash-jdbcstatic.conf

More information : 
With the above configuration, here is the output for on a local install "./logstash --config.debug -f ../config/logstash-jdbcstatic.conf --debug --log.level=debug"
```
[2018-04-17T11:57:29,832][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"jdbc_static", :type=>"filter", :class=>LogStash::Filters::JdbcStatic}
[2018-04-17T11:57:30,010][ERROR][logstash.filters.jdbcstatic] Invalid setting for jdbc_static filter plugin:

  filter {
    jdbc_static {
      # This setting must be a path
      # File does not exist or cannot be opened /Users/julien/Downloads/logstash-6.2.3/config/mysql-connector-java-5.1.45-bin.jar,/Users/julien/Downloads/logstash-6.2.3/config/mysql-connector-java-5.1.45-bin.jar
      jdbc_driver_library => "/Users/julien/Downloads/logstash-6.2.3/config/mysql-connector-java-5.1.45-bin.jar,/Users/julien/Downloads/logstash-6.2.3/config/mysql-connector-java-5.1.45-bin.jar"
      ...
    }
  }
[2018-04-17T11:57:30,020][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Something is wrong with your configuration.", :backtrace=>["/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/config/mixin.rb:89:in `config_init'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/filters/base.rb:128:in `initialize'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/filter_delegator.rb:22:in `initialize'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/plugins/plugin_factory.rb:87:in `plugin'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/pipeline.rb:112:in `plugin'", "(eval):12:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/pipeline.rb:84:in `initialize'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/pipeline.rb:169:in `initialize'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/agent.rb:315:in `block in converge_state'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/agent.rb:312:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/agent.rb:299:in `converge_state'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/Users/julien/Downloads/logstash-6.2.3/logstash-core/lib/logstash/runner.rb:348:in `block in execute'", "/Users/julien/Downloads/logstash-6.2.3/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```

**Comment by guyboertje** [comment]
I will squeeze this fix into #19
